using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using nashira_backend.Data.Db;

namespace nashira_backend.Services.Ai.Tools.Handlers;

// The catalogue of documents this system has produced. Read → autonomous.
//
// Until this existed the agent could write a report and never look at one again: the
// only route to /api/reports was execute_operation against the na_notifications spec,
// which meant knowing the spec was there, and the only route to an export it had just
// generated was none at all. Asked "what did that report say", it answered that it had
// no access — about a document it had written itself minutes earlier.
//
// Two stores, one listing, because the distinction is ours and not the user's: a
// ReportArtifact is a persisted, attributable document (visible in /reports, with an
// expiry), an ExportArtifact is the file handed to whoever asked. Both are "the report
// you made" in the sentence a user actually types.
public sealed class ListReportsHandler : IToolHandler
{
    private static readonly JsonElement Schema = JsonDocument.Parse("""
        {"type":"object","properties":{
          "source":{"type":"string","enum":["reports","exports","all"],"default":"reports","description":"reports = persisted reports (/reports); exports = files produced by export_document/export_table; all = both"},
          "workflow_run_id":{"type":"string","description":"Only reports produced by this workflow run"},
          "search":{"type":"string","description":"Case-insensitive substring of the title or file name"},
          "include_expired":{"type":"boolean","default":false,"description":"Include reports past their retention date"},
          "limit":{"type":"integer","minimum":1,"maximum":100,"default":25}
        },"additionalProperties":false}
        """).RootElement.Clone();

    private readonly AppDbContext _db;

    public ListReportsHandler(AppDbContext db) => _db = db;

    public string Name => "list_reports";
    public string Description =>
        "Lists the documents this system has produced: persisted reports (/reports) and, with " +
        "source='exports' or 'all', the files generated by export_document / export_table. Returns " +
        "id, title, format, size and a download link per item, plus `readable` — whether read_report " +
        "can return its text. Use it to find a report before reading it with read_report.";
    public JsonElement ParametersSchema => Schema;

    public async Task<JsonElement> ExecuteAsync(JsonElement args, CancellationToken ct)
    {
        var source = (Str(args, "source") ?? "reports").Trim().ToLowerInvariant();
        if (source is not ("reports" or "exports" or "all"))
            return Err("source must be 'reports', 'exports' or 'all'");

        var runId = Str(args, "workflow_run_id");
        Guid? runGuid = null;
        if (!string.IsNullOrWhiteSpace(runId))
        {
            if (!Guid.TryParse(runId, out var parsed)) return Err($"'{runId}' is not a valid workflow_run_id");
            runGuid = parsed;
        }

        var search = Str(args, "search")?.Trim().ToLowerInvariant();
        var includeExpired = args.TryGetProperty("include_expired", out var ie) && ie.ValueKind == JsonValueKind.True;
        var limit = args.TryGetProperty("limit", out var l) && l.TryGetInt32(out var lv) ? Math.Clamp(lv, 1, 100) : 25;

        var now = DateTime.UtcNow;
        var items = new List<Item>();

        if (source is "reports" or "all")
        {
            var q = _db.ReportArtifacts.AsNoTracking().Where(r => r.IsActive);
            // Same filter the list endpoint applies: RetentionHostedService sweeps hourly,
            // so between expiry and the sweep a report is gone as far as anyone is
            // concerned, and the agent must not cite one.
            if (!includeExpired) q = q.Where(r => r.ExpiresAt == null || r.ExpiresAt > now);
            if (runGuid is { } rg) q = q.Where(r => r.WorkflowRunId == rg);
            if (!string.IsNullOrEmpty(search))
                q = q.Where(r => r.Title.ToLower().Contains(search) || r.FileName.ToLower().Contains(search));

            // Content comes back because `readable` needs the first bytes, and taking at
            // most `limit` rows bounds it — the same reason the REST listing projects it away.
            var rows = await q.OrderByDescending(r => r.CreatedAt).Take(limit).ToListAsync(ct);
            items.AddRange(rows.Select(r => new Item(
                "report", r.ReportArtifactId, r.Title, r.FileName, r.ContentType, r.SizeBytes,
                r.WorkflowRunId, r.ExpiresAt, r.CreatedAt,
                DocumentText.IsReadable(r.ContentType, r.Content),
                $"/api/reports/{r.ReportArtifactId}/download")));
        }

        if (source is "exports" or "all")
        {
            // An export carries no title and no run: it is a file name and a moment. The
            // file name goes in `title` too so a mixed listing has one column to scan.
            var q = _db.ExportArtifacts.AsNoTracking().Where(a => a.IsActive);
            if (!string.IsNullOrEmpty(search)) q = q.Where(a => a.FileName.ToLower().Contains(search));

            var rows = await q.OrderByDescending(a => a.CreatedAt).Take(limit).ToListAsync(ct);
            items.AddRange(rows.Select(a => new Item(
                "export", a.ExportArtifactId, a.FileName, a.FileName, a.ContentType, a.SizeBytes,
                null, null, a.CreatedAt,
                DocumentText.IsReadable(a.ContentType, a.Content),
                $"/api/export/{a.ExportArtifactId}/download")));
        }

        var merged = items.OrderByDescending(i => i.CreatedAt).Take(limit).ToList();

        return JsonSerializer.SerializeToElement(new
        {
            reports = merged.Select(i => new
            {
                kind = i.Kind,
                id = i.Id,
                title = i.Title,
                file_name = i.FileName,
                content_type = i.ContentType,
                size_bytes = i.SizeBytes,
                workflow_run_id = i.WorkflowRunId,
                expires_at = i.ExpiresAt,
                created_at = i.CreatedAt,
                readable = i.Readable,
                download_url = i.DownloadUrl,
            }).ToList(),
            count = merged.Count,
            source,
            // Said once here rather than left for the agent to infer from `readable`,
            // which on its own looks like a permission problem.
            note = merged.Any(i => !i.Readable)
                ? "Items with readable=false are rendered files (pdf, xlsx): read_report cannot return their text, only the download link."
                : null,
        });
    }

    private sealed record Item(
        string Kind, Guid Id, string Title, string FileName, string ContentType, long SizeBytes,
        Guid? WorkflowRunId, DateTime? ExpiresAt, DateTime CreatedAt, bool Readable, string DownloadUrl);

    private static string? Str(JsonElement a, string k) =>
        a.TryGetProperty(k, out var v) && v.ValueKind == JsonValueKind.String ? v.GetString() : null;

    private static JsonElement Err(string message) => JsonSerializer.SerializeToElement(new { error = message });
}
