// snake_case tool name -> human label, shared by the tool-call block and the
// confirmation card. Unknown names fall back to a de-underscored form.

const TOOL_LABELS: Record<string, string> = {
	whoami: 'Check identity',
	query_devices: 'Search devices',
	create_device: 'Add a device',
	update_device: 'Update a device',
	delete_device: 'Delete a device',
	bulk_delete_devices: 'Delete devices in bulk',
	bulk_delete_reports: 'Delete reports in bulk',
	bulk_delete_workflows: 'Delete workflows in bulk',
	bulk_delete_snippets: 'Delete snippets in bulk',
	device_ping: 'Ping device',
	device_connect: 'Run SSH commands on a device',
	list_credentials: 'List credentials',
	list_apis: 'List APIs',
	discover_operations: 'Search API operations',
	operation_detail: 'Load operation details',
	execute_operation: 'Call the API',
	list_ai_providers: 'List AI providers',
	search_knowledge: 'Search the knowledge base',
	get_knowledge_article: 'Load knowledge article',
	create_knowledge_article: 'Create knowledge article',
	update_knowledge_article: 'Update knowledge article',
	delete_knowledge_article: 'Delete knowledge article',
	export_table: 'Export data',
	parse_file: 'Parse a file',
	send_email: 'Send an email',
	list_email_folders: 'List mailbox folders',
	list_emails: 'List emails',
	read_email: 'Read an email',
	mark_email: 'Mark email read/unread',
	move_email: 'Move an email',
	archive_email: 'Archive an email',
	delete_email: 'Delete an email',
	sync_netbox_inventory: 'Sync NetBox inventory',
	list_inventory_sources: 'List inventory sources',
	create_inventory_source: 'Add inventory source',
	update_inventory_source: 'Update inventory source',
	delete_inventory_source: 'Delete inventory source',
	list_audit_events: 'Read the audit trail',
	get_audit_event: 'Open an audit event',
	verify_audit: 'Verify the audit chain',
	validate_template: 'Validate a template',
	list_validations: 'List template validations',
	list_workflows: 'List workflows',
	get_workflow: 'Open a workflow',
	run_workflow: 'Run a workflow',
	create_workflow: 'Create a workflow',
	update_workflow: 'Update a workflow',
	delete_workflow: 'Delete a workflow',
	simulate_workflow: 'Simulate a workflow',
	promote_workflow: 'Promote a workflow',
	list_profiles: 'List profiles',
	create_profile: 'Create a profile',
	update_profile: 'Update a profile',
	delete_profile: 'Delete a profile',
	assign_profile: 'Assign a profile',
	list_skills: 'List prompt skills',
	get_skill: 'Open a prompt skill',
	load_skill: 'Load an integration skill',
	create_skill: 'Create a prompt skill',
	update_skill: 'Update a prompt skill',
	delete_skill: 'Delete a prompt skill',
	list_specs: 'List API specs',
	get_spec: 'Open an API spec',
	create_spec: 'Create an API spec',
	update_spec: 'Update an API spec',
	delete_spec: 'Delete an API spec',
	list_learnings: 'List learnings',
	create_learning: 'Create a learning',
	update_learning: 'Update a learning',
	delete_learning: 'Delete a learning',
	list_users: 'List users',
	create_user: 'Create a user',
	update_user: 'Update a user',
	delete_user: 'Delete a user',
	list_permission_domains: 'List permission domains',
	get_user_permissions: 'Read user permissions',
	set_user_permissions: 'Set user permissions',
	list_secrets: 'List secrets',
	set_secret: 'Set a secret',
	clear_secret: 'Clear a secret',
	create_credential: 'Create a credential',
	update_credential: 'Update a credential',
	delete_credential: 'Delete a credential',
	create_ai_provider: 'Create an AI provider',
	update_ai_provider: 'Update an AI provider',
	delete_ai_provider: 'Delete an AI provider',
	git_list_repositories: 'List repositories',
	git_list_files: 'List files',
	git_read_file: 'Read a file',
	git_write_file: 'Write a file',
	git_diff: 'Compare changes',
	git_commit_push: 'Commit and push',
	git_status: 'Check repository status',
	git_list_branches: 'List branches',
	git_checkout: 'Switch branch',
	github_create_repo: 'Create a GitHub repository',
	github_create_pr: 'Open a pull request',
	github_merge_pr: 'Merge a pull request',
	git_pull: 'Pull from remote'
};

export function toolLabel(name: string): string {
	return TOOL_LABELS[name] ?? name.replace(/_/g, ' ');
}
